# Generated by Django 4.2.7 on 2023-11-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=50)),
                ('Mobile', models.IntegerField(max_length=20)),
                ('Password', models.TextField(max_length=20)),
                ('Confirm_Password', models.CharField(max_length=20)),
            ],
        ),
    ]
