# Generated by Django 4.2.7 on 2023-11-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='user_Registration',
        ),
    ]
