# Generated by Django 4.2.7 on 2023-11-22 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0002_rename_product_user_registration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_registration",
            name="Email",
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="user_registration",
            name="Mobile",
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name="aut_user_register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("mobile", models.CharField(max_length=200)),
                ("password1", models.CharField(max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
