# Generated by Django 4.2.7 on 2023-11-05 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_from', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='department_name',
            new_name='Doctor_Depert_name',
        ),
    ]
