# Generated by Django 4.2.7 on 2023-11-06 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_from', '0002_rename_department_name_doctor_depert_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubDisease',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_from.doctor_depert_name')),
            ],
        ),
    ]
