# Generated by Django 4.2.7 on 2023-11-06 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_from', '0003_subdisease'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubDisease',
            new_name='Sub_Disease',
        ),
    ]
