# Generated by Django 4.2.7 on 2023-11-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_from', '0004_rename_subdisease_sub_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_disease',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
