# Generated by Django 4.2.7 on 2023-11-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_from', '0005_alter_sub_disease_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_disease',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
