# Generated by Django 4.2.7 on 2023-11-06 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_from', '0006_alter_sub_disease_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_disease',
            name='dep_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard_from.doctor_depert_name'),
        ),
    ]
