# Generated by Django 4.2.7 on 2023-11-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_from', '0007_alter_sub_disease_dep_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_depert_name',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
