# Generated by Django 4.2.7 on 2023-11-06 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_from', '0008_alter_doctor_depert_name_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_disease',
            old_name='name',
            new_name='nam',
        ),
    ]
