# Generated by Django 4.2.7 on 2023-11-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='Symptom1',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='Symptom2',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='Symptom3',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='Symptom4',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='Symptom5',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='Symptom6',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='Symptom7',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='Symptom8',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='Symptom9',
        ),
        migrations.AddField(
            model_name='symptom',
            name='symptom1',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='symptom2',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='symptom3',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='symptom4',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='symptom5',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='symptom6',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='symptom7',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='symptom8',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='symptom9',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
