# Generated by Django 4.2.7 on 2023-11-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0002_remove_symptom_symptom1_remove_symptom_symptom2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='symptom10',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='symptom11',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='symptom12',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='symptom13',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='symptom14',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='symptom15',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='symptom16',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='symptom17',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
